apiVersion: v1
kind: Template
metadata:
  name: onprem-custom-backend
objects:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "onprem-custom-backend-${TARGET_INSTANCE}"
    namespace: ${NAMESPACE}
  spec:
    source:
      git:
        uri: ${GIT_REPO}
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: onprem-custom-backend/Jenkinsfile
        env:
          - name: SECRET_NAME
            value: ${SECRET_NAME}
          - name: NAMESPACE
            value: ${NAMESPACE}
          - name: TARGET_INSTANCE
            value: ${TARGET_INSTANCE}
          - name: DEVELOPER_ACCOUNT_ID
            value: ${DEVELOPER_ACCOUNT_ID}
          - name: PRIVATE_BASE_URL
            value: ${PRIVATE_BASE_URL}
          - name: PRIVATE_BASE_OPENAPI
            value: ${PRIVATE_BASE_OPENAPI}
          - name: PRIVATE_BASE_INTEGRATION_TEST
            value: ${PRIVATE_BASE_INTEGRATION_TEST}
          - name: DISABLE_TLS_VALIDATION
            value: ${DISABLE_TLS_VALIDATION}
parameters:
- name: SECRET_NAME
  value: 3scale-toolbox
- name: NAMESPACE
  value: api-lifecycle
- name: TARGET_INSTANCE
  required: true
- name: GIT_REPO
  value: https://github.com/developertyrone/3scale-toolbox-jenkins-samples.git
- name: DEVELOPER_ACCOUNT_ID
  required: true
- name: PRIVATE_BASE_URL
  required: true
- name: PRIVATE_BASE_OPENAPI
  required: true
- name: PRIVATE_BASE_INTEGRATION_TEST
  required: true
- name: DISABLE_TLS_VALIDATION
  value: "no"
